//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int RoomTypesId { get; set; }
        public int SchoolsId { get; set; }
        public int Amount { get; set; }
    
        public virtual RoomTypes RoomTypes { get; set; }
        public virtual Schools Schools { get; set; }
    }
}
